..\Debug\GraphCreator.exe -F test0.json -l -a  bfs -S V0 -T V0 > results\test_results_bfs0.txt 
..\Debug\GraphCreator.exe -F test1.json -l -a  bfs -S V0 -T V0 > results\test_results_bfs1.txt
..\Debug\GraphCreator.exe -F test2.json -l -a  bfs -S V0 -T V1 > results\test_results_bfs2.txt
..\Debug\GraphCreator.exe -F test3.json -l -a  bfs -S V0 -T V1 > results\test_results_bfs3.txt 
..\Debug\GraphCreator.exe -F test4.json -l -a  bfs -S V0 -T V1 > results\test_results_bfs4.txt
..\Debug\GraphCreator.exe -F test5.json -l -a  bfs -S V0 -T V1 > results\test_results_bfs5.txt 
..\Debug\GraphCreator.exe -F test6.json -l -a  bfs -S V0 -T V1 > results\test_results_bfs6.txt
..\Debug\GraphCreator.exe -F test7.json -l -a  bfs -S V0 -T V1 > results\test_results_bfs7.txt
..\Debug\GraphCreator.exe -F test0.json -l -a  dfs -S V0 -T V0 > results\test_results_dfs0.txt 
..\Debug\GraphCreator.exe -F test1.json -l -a  dfs -S V0 -T V0 > results\test_results_dfs1.txt
..\Debug\GraphCreator.exe -F test2.json -l -a  dfs -S V0 -T V1 > results\test_results_dfs2.txt
..\Debug\GraphCreator.exe -F test3.json -l -a  dfs -S V0 -T V1 > results\test_results_dfs3.txt 
..\Debug\GraphCreator.exe -F test4.json -l -a  dfs -S V0 -T V1 > results\test_results_dfs4.txt
..\Debug\GraphCreator.exe -F test5.json -l -a  dfs -S V0 -T V1 > results\test_results_dfs5.txt 
..\Debug\GraphCreator.exe -F test6.json -l -a  dfs -S V0 -T V1 > results\test_results_dfs6.txt
..\Debug\GraphCreator.exe -F test7.json -l -a  dfs -S V0 -T V1 > results\test_results_dfs7.txt
..\Debug\GraphCreator.exe -F test0.json -l -a  bellman-ford -S V0 -T V0 > results\test_results_bf0.txt 
..\Debug\GraphCreator.exe -F test1.json -l -a  bellman-ford -S V0 -T V0 > results\test_results_bf1.txt
..\Debug\GraphCreator.exe -F test2.json -l -a  bellman-ford -S V0 -T V1 > results\test_results_bf2.txt
..\Debug\GraphCreator.exe -F test3.json -l -a  bellman-ford -S V0 -T V1 > results\test_results_bf3.txt 
..\Debug\GraphCreator.exe -F test4.json -l -a  bellman-ford -S V0 -T V1 > results\test_results_bf4.txt
..\Debug\GraphCreator.exe -F test5.json -l -a  bellman-ford -S V0 -T V1 > results\test_results_bf5.txt 
..\Debug\GraphCreator.exe -F test6.json -l -a  bellman-ford -S V0 -T V1 > results\test_results_bf6.txt
..\Debug\GraphCreator.exe -F test7.json -l -a  bellman-ford -S V0 -T V1 > results\test_results_bf7.txt
..\Debug\GraphCreator.exe -F test0.json -l -a  dijkstra -S V0 -T V0 > results\test_results_d0.txt 
..\Debug\GraphCreator.exe -F test1.json -l -a  dijkstra -S V0 -T V0 > results\test_results_d1.txt
..\Debug\GraphCreator.exe -F test2.json -l -a  dijkstra -S V0 -T V1 > results\test_results_d2.txt
..\Debug\GraphCreator.exe -F test3.json -l -a  dijkstra -S V0 -T V1 > results\test_results_d3.txt 
..\Debug\GraphCreator.exe -F test4.json -l -a  dijkstra -S V0 -T V1 > results\test_results_d4.txt
..\Debug\GraphCreator.exe -F test5.json -l -a  dijkstra -S V0 -T V1 > results\test_results_d5.txt 
..\Debug\GraphCreator.exe -F test6.json -l -a  dijkstra -S V0 -T V1 > results\test_results_d6.txt
..\Debug\GraphCreator.exe -F test7.json -l -a  dijkstra -S V0 -T V1 > results\test_results_d7.txt
..\Debug\GraphCreator.exe -F test0.json -l -a  fast-dijkstra -S V0 -T V0 > results\test_results_fd0.txt 
..\Debug\GraphCreator.exe -F test1.json -l -a  fast-dijkstra -S V0 -T V0 > results\test_results_fd1.txt
..\Debug\GraphCreator.exe -F test2.json -l -a  fast-dijkstra -S V0 -T V1 > results\test_results_fd2.txt
..\Debug\GraphCreator.exe -F test3.json -l -a  fast-dijkstra -S V0 -T V1 > results\test_results_fd3.txt 
..\Debug\GraphCreator.exe -F test4.json -l -a  fast-dijkstra -S V0 -T V1 > results\test_results_fd4.txt
..\Debug\GraphCreator.exe -F test5.json -l -a  fast-dijkstra -S V0 -T V1 > results\test_results_fd5.txt 
..\Debug\GraphCreator.exe -F test6.json -l -a  fast-dijkstra -S V0 -T V1 > results\test_results_fd6.txt
..\Debug\GraphCreator.exe -F test7.json -l -a  fast-dijkstra -S V0 -T V1 > results\test_results_fd7.txt